[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"
  NETLIFY_USE_YARN = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"
    Content-Security-Policy = """
      default-src 'self' https://*.mapbox.com https://*.supabase.co;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.mapbox.com;
      style-src 'self' 'unsafe-inline' https://*.mapbox.com;
      img-src 'self' data: blob: https://*.mapbox.com https://images.unsplash.com;
      connect-src 'self' https://*.mapbox.com https://*.supabase.co;
      worker-src 'self' blob:;
      """

# Asset caching strategy
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"

# Enable brotli and gzip compression
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# HTTP/2 Push headers for critical assets
[[headers]]
  for = "/"
  [headers.values]
    Link = "</assets/index.js>; rel=preload; as=script, </assets/index.css>; rel=preload; as=style"