name: Documentation Update
description: Suggest improvements or report issues in documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation!
        
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs updating?
      options:
        - README
        - API Documentation
        - Code Comments
        - Usage Examples
        - Architecture Guide
        - Contributing Guide
        - Other
    validations:
      required: true
      
  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: Describe the current documentation state
      placeholder: The current documentation...
    validations:
      required: true
      
  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: Describe what should be changed or added
      placeholder: The documentation should...
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation update here
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this documentation update, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true