name: Bundle Analysis

on:
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build with Bundle Analysis
      run: npm run build -- --report
      
    - name: Check Bundle Size
      uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        pattern: "dist/**/*.{js,css,html}"
        
    - name: Upload Bundle Analysis
      uses: actions/upload-artifact@v3
      with:
        name: bundle-analysis
        path: dist/stats.html